### ISSUE TITLE
It's possibile to print the battery percentage nearest the icon?

### ISSUE THREAD

**Issue by giusbatt** [valr/cbatticon#18]
As the title.

**Comment by valr** [comment]
Do you mean something like this: http://ubuntuhandbook.org/index.php/2014/07/ubuntu-14-04-show-battery-percentage-time/ ?

**Comment by giusbatt** [comment]
yes but I don't have ubuntu. I'm stay on Arch

**Comment by valr** [comment]
Sure, it was just for the example. I'm an archer as well.
I'll have a look at it.

**Comment by giusbatt** [comment]
thanks!

**Comment by valr** [comment]
I've made some research and found that the GtkStatusIcon used in cbatticon uses the Xembed system tray, which has limitations in the size of icons that can be defined. Also, the GtkStatusIcon is not a real gtk widget but more an emulation of a gtk widget because of Xembed.

It is technically possible to write variable text (like the percentage) in the icon, but not to extend its size to have both the icon and the percentage. I've made a quick test to see if having both the icon and the percentage in a 24x24 icon would work, but it's way too small to be readable (and I will not try creating another icon for the percentage, that would create more problems because e.g. there is no easy way to ensure the sequencing of icons in the tray).

During the research I've made, I've seen as well that in gtk3.14, the GtkStatusIcon widget has been marked as deprecated. Indeed, the old style Xembed system tray is being removed from gtk/gnome in the future and qt/kde as well, to be replaced by new API/libraries. Problem is that the API/libraries to use are far from being accepted everywhere at this time.

Maybe there will be an opportunity to implement your request in the future by using the libappindicator, which seems to be the direction followed by people and apparently contains feature allowing to define text near the icon. But it's too early at this time to go in that direction. In other words...wait and see.

For reference, here is a blog post summarizing possible options for the future: http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/
