### ISSUE TITLE
cbatticon does not execute -c command in a reliable manner

### ISSUE THREAD

**Issue by stef204** [valr/cbatticon#35]
cbatticon 1.6.4 on Linux 4.7.6

The command defined with -c does not seem to execute reliably.
IOW, it has worked at times (few) but mostly has failed to execute.

I use: `cbatticon -r 5 -c 'systemctl suspend' -l 15 -x battery_notify_level`

Result: most of the time, my box does **not** suspend but just gets "killed".  It **has** worked at times but rarely.

Have tried to use backticks, single quotes, double quotes, etc., to no avail but may not have gotten it quite right.

"battery_notify_level" is a tiny script:

```
#!/bin/sh
notify-send "Battery" "$(acpi -b)" -u low
```

Any ideas on how to troubleshoot/fix?

**Comment by valr** [comment]
Hi stef204,

30 seconds before the critical command is executed, there is a message sent to the system logger (e.g. journalctl).

Can you please check in your log if you have something like this: "Spawning critical battery level command in 30 seconds: ...the_command_to_execute..." ? If you have it, can you please send me the exact message?

If running the command failed, you will also see a message like this: "Cannot spawn critical battery level command...". If you have it, can you please send me the exact message?

Can you also run cbatticon in debug mode (option -d) and send me the result? You can e.g. run it for 1 minute and send me the messages from the console.

Thanks

**Comment by stef204** [comment]
My battery is not in great shape--can only hold 15 to 20mns charge--so the original level for "critical" at 5% actually represents a _very_ small amount of time, possibly too short for cbatticon?  Shouldn't be because it takes very little time to execute `systemctl suspend`.

BTW, `systemctl suspend` does works on my system, when issued on cli or called by scripts.  So that is not the problem.

The journal entries are fairly detailed and long, since I have it set to debug level; while I do have `Spawning critical battery level command in 30 seconds: systemctl suspend` I do not see the `Cannot spawn....`

I also see: `[Firmware Bug]: battery: (dis)charge rate invalid.`  Not sure what value this message really has, if any.

I also tested cbatticon `-c` option 3 times today changing the critical level to 10% and then 15%, it worked only once.

Hopefully, you'll be able to see something in the logs--will send those by email together with -d output.

Thanks.

**Comment by stef204** [comment]
Any luck with the info I emailed you?

**Comment by valr** [comment]
Sorry for the delay, I had way too many things at work and home.
I've just checked now.

Regarding the message: "[Firmware Bug]: battery: (dis)charge rate invalid" it happens that some hardware/firmware/drivers have problems and are not able to report the discharge rate. cbatticon has a workaround for those cases and determine the discharge rate itself. You can see it with this message from the debug output: "workaround: current rate is not available, estimating rate".

The debug output from cbatticon looks good, and I guess the system log you've provided is for the case where the system has successfully been suspended.

In the above post, you've mentioned this: "The journal entries are fairly detailed and long, since I have it set to debug level; while I do have Spawning critical battery level command in 30 seconds: systemctl suspend I do not see the Cannot spawn....". In that case, is the system still running for at least 30 seconds? If yes, can you send me the log showing the "Spawning critical battery level command in 30 seconds..." and the next 2 minutes?

Thanks

**Comment by stef204** [comment]
I got a new battery so will try again; perhaps the fact that old battery was almost dead/holding only very little charge had a negative impact.  Will let you know. Thanks.

**Comment by valr** [comment]
Hi @stef204,
Did you had the chance to test the behaviour of cbatticon with your new battery?
Should I keep this issue opened or do you have new information to progress on this?
Thanks

**Comment by stef204** [comment]
@valr 
Let's close this issue; have not tested as using another battery utility more suited to my needs. Thank you.

**Comment by valr** [comment]
Ok, thanks for answering.
I'm closing the issue now.
